server {

    listen 80;

    # In Docker, "localhost" refers to the container itself.
    server_name localhost;

    # --- THE FRONTEND CONNECTION (Static Files) ---
    # Instead of proxying to a Vite cluster (127.0.0.1:5173),
    # Nginx now serves the pre-built static files directly from its own disk.
    location / {
        # This is where our Dockerfile copied the 'dist' folder.
        root /usr/share/nginx/html;
        index index.html;

        # CRITICAL FOR REACT ROUTER:
        # Single Page Apps (SPAs) manage routing in the browser.
        # If a user refreshes 'localhost:8080/dashboard', Nginx won't find
        # a 'dashboard' folder. This line tells Nginx: "If the file doesn't
        # exist, send them index.html and let React handles the rest."
        try_files $uri $uri/ /index.html;
    }

    # --- THE BACKEND CONNECTION (Reverse Proxy) ---
    # This handles any browser requests starting with /api (e.g., /api/v1/login).
    location /api {
        # Because Nginx and FastAPI are in separate containers on the same
        # Docker network, we can use the backend's CONTAINER NAME as the address.
        proxy_pass http://eap-backend-container:8000;

        # Standard headers to ensure the Backend knows the real user's info
        proxy_set_header Host $host;
        proxy_set_header X-Real-IP $remote_addr;
        proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
        proxy_set_header X-Forwarded-Proto $scheme;


    }
}