name: React PR Checks

on:
  pull_request:
    branches: [ "main", "dev" ]

jobs:
  ci:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v6

      - name: Setup Node.js
        uses: actions/setup-node@v6
        with:
          node-version: 24

      - name: Install dependencies
        run: npm install --frozen-lockfile

      - name: Run tests
        run: npm run test:coverage

      - name: Lint project
        run: npm run lint

      - name: Build project
        run: npm run build
